apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: rtf-ingress
  namespace: rtf
  labels:
    mule-environment: environment-id
    mule-business-group: business-group-id
spec:
  ingressClassName: rtf-openshift-default
  rules:
  # host: app-name.router-internal-default.<value specific to your openshift cluster>  - please modify this appropriate to your environment
  - host: app-name.router-internal-default.apps.muledemo2.sandbox.test.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service
              port:
                number: 80
